# Generated by Django 4.2.11 on 2026-04-22 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.IntegerField()),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asia'), ('SA', 'South America'), ('OCE', 'Oceania'), ('ME', 'Middle East')], max_length=10)),
                ('game_mode', models.CharField(choices=[('ranked', 'Ranked'), ('casual', 'Casual'), ('tournament', 'Tournament'), ('practice', 'Practice')], max_length=20)),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queuing', 'In Queue'), ('matched', 'Matched'), ('left', 'Left Queue')], default='queuing', max_length=20)),
                ('elo', models.IntegerField(default=1200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'ordering': ['join_time'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('greedy', 'Greedy'), ('graph', 'Graph')], max_length=20)),
                ('player_count', models.IntegerField()),
                ('matches_made', models.IntegerField()),
                ('avg_skill_gap', models.FloatField()),
                ('avg_wait_time', models.FloatField()),
                ('min_skill_gap', models.FloatField(default=0)),
                ('max_skill_gap', models.FloatField(default=0)),
                ('execution_time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_gap_distribution', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_gap', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=10)),
                ('game_mode', models.CharField(blank=True, max_length=20)),
                ('match_quality', models.FloatField(default=0.0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='matchmaking.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='matchmaking.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_winner', to='matchmaking.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
