# Generated by Django 4.2.11 on 2026-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='p1_elo_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p1_elo_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_elo_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_elo_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='result_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='fairness_score',
            field=models.FloatField(default=0),
        ),
    ]
